### ISSUE TITLE
Does the algorithm take into account direction?

### ISSUE THREAD

**Issue by jdrietz** [Gooong/LeastCostPath#10]
Does the algorithm used take into account direction (i.e. is it anisotropic?)

Thanks,

JR

**Comment by Gooong** [comment]
Hi,

This algorithm takes the neighbor grids equally (is isotropic). It just computes the cost of each grid provided by the cost layer.

**Comment by jdrietz** [comment]
Thanks!

**Comment by jdrietz** [comment]
One quick additional question:  is it possible to get the calculated cost value for a given path in order to compare it with other paths between other locations?

Thanks,

JR
