### ISSUE TITLE
dijsktra_algorithm.py - consider checking if feedback is None before using it

### ISSUE THREAD

**Issue by sebbelese** [Gooong/LeastCostPath#11]
I guess this is not relevant within the QGIS plugin, but the dijkstra function in deikstra_algorithm.py reads:
`def dijkstra(start_tuple, end_tuples, costMap, find_nearest=True, feedback=None):`
which means that feedback is optional. 

However, there is a call to feedback in the function which does not check if feedback exists, resulting in an error if the function is called with the default arguments, e.g.:
`feedback.setProgress(1 + 100 * (1 - bound / total_manhattan))`

It can be an issue if we call the function from a python script, not the QGIS plugin

**Comment by Gooong** [comment]
Hi,

Thanks for your feedback. Will fix this bug soon.

**Comment by Gooong** [comment]
Fixed. Will release soon.
