### ISSUE TITLE
How to cite this plugin in papers?

### ISSUE THREAD

**Issue by momeni133** [Gooong/LeastCostPath#14]
First, thanks for providing such a great QGIS plugin. I found it very helpful!
As I am using your plugin in my research, I need to cite it. Unfortunately, I didn't find any information about how to cite it. I would really appreciate it if you could tell me your preferred citation.
Sorry if it is already provided and I missed it. 

Many thanks!

**Comment by Gooong** [comment]
Hi,

Thanks! You can cite according to this: https://gis.stackexchange.com/questions/396979/how-to-cite-a-qgis-plugin
