### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by bellanz80** [Gooong/LeastCostPath#2]
Hi,
I have an error trying to install the plug. I have tried from the QGIS repository, how to download the ZIP from Github.
Annex screenshot

QGIS: 3.4.2
WINDOWS: 10 64 bit, 1809 - 17763.194
Thank you
Luca
![error](https://user-images.githubusercontent.com/38449926/50164607-c2f35900-02a8-11e9-800e-99389a2acbbc.PNG)

**Comment by Gooong** [comment]
Hi, thank you for your report. We are aware of this issue (probably on Windows) and will try to fix it. 

Temporary you can download the zip file from QGIS Python Plugins Repository: https://plugins.qgis.org/plugins/leastcostpath/ or our release file: https://github.com/Gooong/LeastCostPath/releases

Thanks.

**Comment by bellanz80** [comment]
Thank's! :)

**Comment by Gooong** [comment]
Fixed in v0.2
